version: '3.8'
services:
  server-api:
    image: node:12-alpine
    command: sh -c "npm i && npm run start-dev"
    container_name: server-api
    ports:
      - 5001:5001
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PORT: 5001
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_PORT: 3306
      MYSQL_DB: game
      MYSQL_URI: mysql://root:secret@mysql:3306/game
      MOCK_DB: 'false'

  web-app:
    image: node:12-alpine
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: web-app
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules

  mysql:
    image: mysql:5.7
    volumes:
      - game-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: game

volumes:
  game-mysql-data:
